name: sbucks
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations: 
  #   sdk: flutter         
  
  cupertino_icons: ^1.0.0
  carousel_slider: ^2.3.1
  crypto: ^2.1.5
  pin_code_fields: ^6.0.2
  bubbled_navigation_bar: ^0.0.4
  barcode_widget: ^1.5.0
  flutter_inappwebview: ^4.0.0+4
  flutter_html: ^1.2.0
  # flutter_statusbarcolor:
  fluttertoast: ^7.1.6
  path_provider: ^1.6.27
  path: 1.8.0-nullsafety.1
  camera: ^0.6.4+5
  url_launcher: ^5.7.10
  uuid: ^2.2.2
  shake: ^0.1.0
  # intl: ^0.16.1 
  easy_localization: ^2.3.3
  rxdart: ^0.25.0
  google_maps_flutter: ^1.0.10
  geolocator: ^6.1.13
  dio: ^3.0.10
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+4
  json_annotation: ^3.1.1
  sqflite: ^1.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: 0.4.5
  build_runner: ^1.10.13
  json_serializable: ^3.5.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/img/
    - assets/dummy-image/
    - assets/translations/
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/NunitoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
